name: CI
on:
  push:
  schedule:
  - cron: '0 0 * * 0'
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run benchmarks
      uses: ./.github/action
      with:
        cmd: 'source ./run.zsh'
