name: CI
# on:
#   schedule:
#     - cron: '0 0 * * 0'
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install zsh
      run: sudo apt-get update && sudo apt-get install --no-install-recommends -y zsh
    - name: Run benchmarks
      shell: zsh -i {0}
      run: source ./run.zsh -p out -f vanilla -f antibody-static -f antigen -f oh-my-zsh -f prezto -f zgen -f zim
    - name: Print results
      run: 'tail -n+1 out-results/*.log'
