name: CI
on:
  push:
  schedule:
  - cron: '0 0 * * 0'
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run benchmarks
      uses: ./.github/action
      with:
        cmd: 'source run.zsh -p results'
    - name: Plot graph
      run: 'sudo apt-get install -y --no-install-recommends gnuplot && gnuplot -c plot-graph <(grep -v vanilla results/results.csv | sort -t, -g -k2) > results.svg'
    - uses: actions/upload-artifact@v2
      with:
        path: 'results/results.csv'
    - uses: actions/upload-artifact@v2
      with:
        path: 'results.svg'
